import { create } from 'zustand';

export const languages = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'ta', label: 'தமிழ்' }
];

const translations = {
  en: {
    brand: 'QueueLess',
    staffLogin: 'Staff login',
    userLogin: 'User login',
    userBooking: 'User login and queue booking',
    userBookingSub: 'Choose your purpose, enter your details, and get a live token on your phone.',
    purpose: 'Purpose of queue',
    name: 'Name',
    phone: 'Phone',
    bookQueue: 'Book my queue',
    waitingQueues: 'Waiting for available queues',
    liveToken: 'Your live token',
    queueProgress: 'Queue progress',
    estimatedWait: 'estimated wait',
    landingTitle: 'Make waiting visible, fair, and calmer.',
    landingSub: 'QueueLess gives visitors a virtual token and gives staff a live control room for the next person, the next delay, and the next rush hour.',
    staffConsole: 'Staff login',
    staffHint: 'Use demo staff credentials after MongoDB is seeded: admin@queueless.app / Password123!',
    email: 'Email',
    password: 'Password',
    login: 'Log in',
    operations: 'Operations console',
    operationsTitle: 'Move the queue one clear action at a time.',
    nowServing: 'Now serving',
    callNext: 'Call next person',
    markServed: 'Mark current served',
    nextLine: 'Next in line',
    arrived: 'Arrived',
    membersQueue: 'members in queue',
    hold: 'Hold',
    recall: 'Recall',
    skip: 'Skip',
    message: 'Message',
    voice: 'Voice'
  },
  hi: {
    brand: 'क्यूलैस',
    staffLogin: 'स्टाफ लॉगिन',
    userLogin: 'यूज़र लॉगिन',
    userBooking: 'यूज़र लॉगिन और कतार बुकिंग',
    userBookingSub: 'अपना काम चुनें, विवरण भरें, और फोन पर लाइव टोकन पाएं।',
    purpose: 'कतार का उद्देश्य',
    name: 'नाम',
    phone: 'फोन नंबर',
    bookQueue: 'मेरी कतार बुक करें',
    waitingQueues: 'उपलब्ध कतारों की प्रतीक्षा',
    liveToken: 'आपका लाइव टोकन',
    queueProgress: 'कतार प्रगति',
    estimatedWait: 'अनुमानित प्रतीक्षा',
    landingTitle: 'प्रतीक्षा को साफ, न्यायपूर्ण और शांत बनाएं।',
    landingSub: 'QueueLess विज़िटर को वर्चुअल टोकन और स्टाफ को लाइव कंट्रोल रूम देता है।',
    staffConsole: 'स्टाफ लॉगिन',
    staffHint: 'MongoDB seed के बाद डेमो लॉगिन इस्तेमाल करें: admin@queueless.app / Password123!',
    email: 'ईमेल',
    password: 'पासवर्ड',
    login: 'लॉग इन',
    operations: 'ऑपरेशन कंसोल',
    operationsTitle: 'कतार को एक-एक स्पष्ट कदम से आगे बढ़ाएं।',
    nowServing: 'अभी बुलाया जा रहा है',
    callNext: 'अगले व्यक्ति को बुलाएं',
    markServed: 'मौजूदा टोकन पूरा करें',
    nextLine: 'अगले लोग',
    arrived: 'आए',
    membersQueue: 'कतार में लोग',
    hold: 'रोकें',
    recall: 'फिर बुलाएं',
    skip: 'छोड़ें',
    message: 'संदेश',
    voice: 'आवाज़'
  },
  ta: {
    brand: 'கியூலெஸ்',
    staffLogin: 'ஸ்டாஃப் உள்நுழைவு',
    userLogin: 'பயனர் உள்நுழைவு',
    userBooking: 'பயனர் உள்நுழைவு மற்றும் வரிசை பதிவு',
    userBookingSub: 'உங்கள் தேவையை தேர்வு செய்து, விவரங்களை நிரப்பி, நேரடி டோக்கனை பெறுங்கள்.',
    purpose: 'வரிசையின் நோக்கம்',
    name: 'பெயர்',
    phone: 'தொலைபேசி எண்',
    bookQueue: 'என் வரிசையை பதிவு செய்',
    waitingQueues: 'வரிசைகள் கிடைக்க காத்திருக்கிறது',
    liveToken: 'உங்கள் நேரடி டோக்கன்',
    queueProgress: 'வரிசை முன்னேற்றம்',
    estimatedWait: 'மதிப்பிடப்பட்ட காத்திருப்பு',
    landingTitle: 'காத்திருப்பை தெளிவாகவும் நியாயமாகவும் அமைதியாகவும் மாற்றுங்கள்.',
    landingSub: 'QueueLess பயனர்களுக்கு மெய்நிகர் டோக்கனையும், ஸ்டாஃபுக்கு நேரடி கட்டுப்பாட்டு மையத்தையும் தருகிறது.',
    staffConsole: 'ஸ்டாஃப் உள்நுழைவு',
    staffHint: 'MongoDB seed செய்த பிறகு டெமோ உள்நுழைவு: admin@queueless.app / Password123!',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    login: 'உள்நுழை',
    operations: 'செயல்பாட்டு கட்டுப்பாடு',
    operationsTitle: 'வரிசையை ஒரு தெளிவான நடவடிக்கையாக முன்னேற்றுங்கள்.',
    nowServing: 'இப்போது அழைக்கப்படுகிறது',
    callNext: 'அடுத்தவரை அழை',
    markServed: 'தற்போதைய டோக்கன் முடிந்தது',
    nextLine: 'அடுத்தவர்கள்',
    arrived: 'வந்த நேரம்',
    membersQueue: 'வரிசையில் உள்ளவர்கள்',
    hold: 'நிறுத்து',
    recall: 'மீண்டும் அழை',
    skip: 'தவிர்',
    message: 'செய்தி',
    voice: 'குரல்'
  }
};

export const useLanguageStore = create((set, get) => ({
  language: localStorage.getItem('ql_language') || 'en',
  setLanguage: (language) => {
    localStorage.setItem('ql_language', language);
    set({ language });
  },
  t: (key) => translations[get().language]?.[key] || translations.en[key] || key
}));
